name: robotnik_simulation_ws

services:
  robotnik_simulation_devel:
    container_name: robotnik_simulation_devel
    image: robotnik_simulation:jazzy-devel
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        USER_UID: ${LOCAL_UID:-1000}
        USER_GID: ${LOCAL_GID:-1000}
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      DISPLAY: ${DISPLAY}
      ROS_DISTRO: jazzy
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      WORKSPACE_DIR: /home/robot/ros2_ws
      SRC_DIR: /home/robot/ros2_ws/src
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - workspace_src:/home/robot/ros2_ws/src
      - workspace_build:/home/robot/ros2_ws/build
      - workspace_install:/home/robot/ros2_ws/install
      - workspace_log:/home/robot/ros2_ws/log
      - ../:/home/robot/ros2_ws/src/robotnik/robotnik_simulation
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["sleep", "infinity"]

volumes:
  workspace_src:
  workspace_build:
  workspace_install:
  workspace_log:
