<?xml version="1.0"?>
<?xml-model
  href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robotnik_simulation_bringup</name>
  <version>1.0.0</version>
  <description>Package to bring up the robotnik simulation</description>
  <maintainer email="ros-developers@robotnik.es">Robotnik Developers</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>robotnik_description</exec_depend>
  <exec_depend>robotnik_gazebo_ignition</exec_depend>
  <exec_depend>robotnik_simulation_localization</exec_depend>
  <exec_depend>robotnik_simulation_navigation</exec_depend>
  <exec_depend>robotnik_simulation_moveit</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>teleop_panel</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
